### ISSUE TITLE
Error - Python3 - Advantage Database11.10 

### ISSUE THREAD

**Issue by einzelfabrik** [ChrisCPoirier/adsdb#7]
Hello, I was pleased when I found your project - because I currently have the issue that I need to talk to a database from Python - have tried it so far via the qsqlcmd.exe - but here unfortunately not everything works. Therefore, I liked your approach of course better. I have installed everything and created path variables. Unfortunately, I get the following error when running my test:

C:\Users\admin\PycharmProjects\EC-WA>python adspy.py **"Select * From AKgruppe"**
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\EC-WA\adspy.py", line 35, in <module>
    main()
  File "C:\Users\admin\PycharmProjects\EC-WA\adspy.py", line 13, in main
    conn = adsdb.connect(DataSource='\\server:6262\DB.add', ServerType='remote', UserID='ADSSYS')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\adsdb.py", line 411, in connect
    return Connection(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\adsdb.py", line 447, in __init__
    raise error
adsdb.OperationalError: b'Error 6080:  Error loading the Advantage remote communication layer DLL.  axServerConnect'

**Comment by einzelfabrik** [comment]
Solution: Copy axcws64.dll to Python Root

**Comment by einzelfabrik** [comment]
Solution: Copy axcws64.dll to Python Root
